floor_policy:
  mode: pure_no_fees
  lcr_min: 1.00
  lcr_target: 1.00
  defended_quantity: circulating_supply
  public_note: >
    Floor excludes gas/platform fees; execution triggers subtract venue frictions.
    External venues may print below floor due to fees; own platform typically closer to floor.

execution_friction:
  discovery_mode: true
  trigger_formula: "F_pure - (fee_fix + fee_pct*F_pure + gas + slippage)"
  venues: []  # filled by discovery phase

threshold_discovery:
  drawdown_curve:
    q_list: [0.01, 0.005, 0.001]
  twap_window_days: [3, 7, 14]
  trigger_pct: [0.03, 0.05, 0.065, 0.08, 0.10]
  persistence_hours: [2, 4, 6, 8]
  divergence_gate_pct: [0.5, 0.75, 1.0]
  spend_caps_reserve_pct_event: [0.05, 0.075, 0.10]
  spend_caps_reserve_pct_day: [0.15, 0.20, 0.25]

robust_selection:
  evt:
    method: pot
    u_percentile: 0.95
    diagnostics: ["qq", "mean_excess"]
  importance_sampling:
    tail_bias: ["jump_cluster", "spread_widening", "depth_drought"]
  dro:
    ambiguity: {type: "wasserstein", radius: "bootstrap_auto"}
  nested_validation:
    scenario_folds: 5
    time_splits: ["early", "late"]
  stability_regularizer:
    outcome_variance_weight: 0.1

mission_tiers:
  tier0: ["no_lcr_violations", "crash_within_empirical_band"]
  tier1: ["min_tail_drawdown_q995"]
  tier2: ["min_recovery_median", "min_recovery_p95"]
  tier3: ["min_reserve_drain", "min_exec_cost_bps"]
  tier4: ["max_pure_floor_cagr"]

metadata:
  spec_version: 0.1
  notes: "Initial NOVA config honoring pure floor + fee-aware execution."
